### ISSUE TITLE
Add Windows for pikepdf in conda-forge?

### ISSUE THREAD

**Issue by LaughingFishTale** [conda-forge/pikepdf-feedstock#113]
### Comment:

Pip has pikepdf for Linux, Mac, and Windows. The wheel files are out there for all three operating systems. But in conda-forge, currently it's only available for Linux and Mac. Could we add in Windows support, please? Thank you!

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Depends on https://github.com/conda-forge/qpdf-feedstock/issues/12

**Comment by LaughingFishTale** [comment]
THANK YOU!! This is terrific.

**Comment by jakirkham** [comment]
Happy to help :)
